name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "Awaiting Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Outage
        - Wish
        - Feature
        - Task
        - Test
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      multiple: true
      description: What component was effected?
      options:
        - sdk-go
        - sdk-java
        - sdk-python
        - website
        - beam-community
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
